ItvedantProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('student.urls','student'),namespace='student')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v
from .form import *
from django.contrib.auth import views as auth_v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_v.LoginView.as_view(), name='login'),
    path('',v.login_view),
    path('dashboard',v.home,name='dashboard'),
    path('openingDetails/<int:cid>',v.openingDetail,name='openingDetail'),
    path('profile',v.profile_view,name='profile'),
    path('interview-course',v.interview_view,name='interview'),
    # path('aws-interview',v.aws,name='aws'),
    path('register',v.register_view,name='register'),
    path('login_view',v.login_view,name='login_view'),
    path('logout',v.logout_view,name='logout'),
    path('sql-study-material/<int:id>/',v.sqlStudy,name='sqlContent'),
    path('study-material/<int:id>/', v.study_material_view, name='study_material'),
    path('wd-interview/<int:id>/',v.wd,name='wdcontent'),
    path('search',v.searchView,name='intSearch'),
    # path('edit/<int:pk>',v.editProfile.as_view()),
    
    path('courses',v.course,name='course'),
    path('news',v.news,name='news'),
    path('news-search',v.news_search,name='newsSearch'),
    # path('cart',v.cart,name='cart'),
    path('addcart/<int:cid>/',v.add_to_cart,name='addcart'),
    path('cartlist',v.cart_list,name='cartlist'),
    # path('success',v.success_view,name='success'),

    path('update_cart/<int:item_id>/<str:action>/', v.update_cart, name='update_cart'),
    path('delete_from_cart/<int:item_id>/', v.delete_from_cart, name='delete_from_cart'),
    path('recognize_speech/', v.recognize_speech, name='recognize_speech'),



    path('courseSort/<str:category>/',v.sort,name='sort'),

    path('success/', v.payment_success, name='success'),
    

   path('password_reset/', auth_v.PasswordResetView.as_view(template_name='password_reset_form.html', success_url='/password_reset_done'), name='password_reset'),

    path('password_reset_done', auth_v.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/',auth_v.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', success_url='/password_reset_complete'), name='password_reset_confirm'),

    path('password_reset_complete', auth_v.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html',), name='password_reset_complete'),
]

student/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from .models import *
import requests
import razorpay
from django.views.decorators.csrf import csrf_exempt
import speech_recognition as sr
from django.http import JsonResponse
from django.contrib import messages
from django.http import HttpResponseBadRequest,HttpResponse
# Create your views here.

# Home View Starts#
@login_required
def home(request):
    modules=module.objects.all()
    openings1 = openings.objects.all()
    # profiles=profile.objects.all()
    # progress_percentage = 0.0
    try:
        f = profile.objects.get(user=request.user)
    except profile.DoesNotExist:
        f = None
    module_progress={}
    if request.user.is_authenticated:
        for mod in modules:
            total_topics = StudyTopic.objects.filter(module=mod).count()
            if total_topics > 0:
                completed_topics = SubtopicProgress.objects.filter(user=request.user, completed=True, topic__module=mod).count()
                progress_percentage = (completed_topics / total_topics) * 100
            else:
                progress_percentage=0.0
            module_progress[mod] = progress_percentage
    context={'modules':modules,'openings':openings1,'profile':f,'progress_percentage':progress_percentage,'module_progress':module_progress}
    return render(request,"home.html",context)

# Home View Ends#

def openingDetail(request,cid):
    return render(request,'jobDetail.html'),

# Profile View Starts #

# @login_required
def profile_view(request):
    if request.method=="POST":
        user = request.user
        # uid=request.session.get('uid')
        firstname=request.POST.get('firstname')
        middlename=request.POST.get('middlename')
        lastname=request.POST.get('lastname')
        email=request.POST.get('myemail')
        mobile=request.POST.get('mobile')
        dob=request.POST.get('dob')
        gender=request.POST.get('gender')
        address=request.POST.get('address')
        guardian=request.POST.get('guardian')
        contact=request.POST.get('contact')
        img =request.FILES.get('img')
        fileUpload =request.FILES.get('fileUpload')
        f, created = profile.objects.get_or_create(user=user)
        f.firstname=firstname
        f.middlename=middlename
        f.lastname=lastname
        f.email=email
        f.mobile=mobile
        f.dob=dob
        f.gender=gender
        f.address=address
        f.guardian=guardian
        f.contact=contact
        
        if img:
            f.img=img

        if fileUpload:
            f.fileUpload = fileUpload
        f.save()
        
        messages.info(request,"Profile Updated Successfully.")
        return redirect('/profile')
    else:
        # user = request.user
        # f=profile.objects.get_or_create(user=user)
        try:
            f = profile.objects.get(user=request.user)
        except profile.DoesNotExist:
            f = None
        context={'profile':f}
        return render(request,'profile.html',context)

# Profile View Ends #

# Interview Questions View Starts#

def interview_view(request):
    # int_id = get_object_or_404(Interview,id=id)
    interviews=Interview.objects.all()
    f = profile.objects.get(user=request.user)
    context={'interviews':interviews,'profile':f}
    return render(request,'interview.html',context)

# Interview Questions View Ends#
# Registration View Starts#

# def register_view(request):
#     if request.method=="POST":
#         f=UserCreationForm(request.POST)
#         f.save()
#         return redirect('/profile')
#     else:
#         f=UserCreationForm
#         context={'form':f}
#         return render(request,'register.html',context)

# def register_view(request):
#     if request.method == "POST":
#         f = UserCreationForm(request.POST)
#         if f.is_valid():
#             user = f.save()
#             # Authenticate the user
#             username = f.cleaned_data.get('username')
#             raw_password = f.cleaned_data.get('password1')
#             user = authenticate(username=username, password=raw_password)
#             if user is not None:
#                 # Log the user in
#                 login(request, user)
#                 # Redirect to the profile page
#                 return redirect('/profile')
#     else:
#         f = UserCreationForm()
#         context = {'form': f}
#         return render(request, 'register.html', context)

def register_view(request):
    # logic
    if request.method == "POST":

        uname = request.POST.get("username")
        email = request.POST.get("email")
        fname = request.POST.get("fname")
        lname = request.POST.get("lname")
        pass1 = request.POST.get("pass1")
        cpass = request.POST.get("pass2")
        # print(uname,email,fname,lname,pass1,cpass)

# check wheater user exists or not
        if(pass1 != cpass):
            messages.warning(request,"Password is'nt Matching")
            return redirect("/register")

        try:
            if User.objects.get(username=email):
                messages.info(request,"Username is taken..")
                return redirect("/register")
        except:
            pass

        myuser = User.objects.create_user(username=email, password=pass1)
        myuser.first_name = fname
        myuser.last_name = lname

        myuser.save()

        user = authenticate(request, username=email, password=pass1)
        if user is not None:
            login(request, user)
            messages.success(request, "Signup and Login Success")
            return redirect("/profile")  # Redirect to profile page

        messages.error(request,"Something went wrong")
        return redirect("/register")

    return render(request, "register.html")

    
# Registration View Ends#

# Login View Starts #

def login_view(request):
    if request.method=="POST":
        uname=request.POST.get('username')
        passw=request.POST.get('password')

        user=authenticate(request,username=uname,password=passw)
        if user is not None:
            request.session['uid']=user.id
            login(request,user)
            messages.info(request,"Login Successful")
            return redirect('/dashboard')
        else:
            f=LoginForm
            context={'form':f}
            messages.error(request,"Invalid Credentials, Please Enter correct email and password.")
            return render(request,'login.html',context)
    else:
        f=LoginForm
        context={'form':f}
        return render(request,'login.html',context)
    
# Login View Ends #

# Logout View Starts #
def logout_view(request):
    logout(request)
    messages.success(request,'Logout successful')
    return redirect('/login_view')
# Logout View Ends #

def wd(request,id):
    int_id = get_object_or_404(Interview,id=id)
    f=InterviewQuestions.objects.filter(moduleName=int_id)
    p = profile.objects.get(user=request.user)
    context={'f':f,'profile':p}
    return render(request,'wd.html',context)


from django.db.models import Q
def searchView(request):
    srch=request.POST.get('src')
    inte=InterviewQuestions.objects.filter(Q(ans__contains=srch) | Q(ques__contains=srch))
    context={'f':inte}

    context = {'f': inte}

    if srch=="": 
        return redirect('/wd-interview') 
    
    # elif srch != query:
    #     messages.info(request,'No results found')
    #     return redirect('/wd-interview')
    else:
        messages.success(request,'Your Search Results:')
        return render(request,'wd.html',context)
    

def sqlStudy(request,id):
    main_topics = StudyTopic.objects.filter(module=id)
    f = profile.objects.get(user=request.user)
    modul = get_object_or_404(module, id=id)
    topics_with_materials = [(topic, StudyMaterial.objects.filter(studytopic=topic)) for topic in main_topics]
    return render(request,'sqlStudy.html',{'modul':modul,'topics_with_materials':topics_with_materials,'profile':f})

def study_material_view(request,id):
    # Getting material
    material = get_object_or_404(StudyMaterial, id=id)

    # Getting All Subtopics
    all_subtopics = StudyMaterial.objects.filter(studytopic=material.studytopic).order_by('id')

    # Getting Next Material
    next_material = StudyMaterial.objects.filter(id__gt=material.id,studytopic=material.studytopic).order_by('id').first()

    # Checking If it is last Subtopic
    is_last_subtopic = next_material is None

    # Getting profile data of logged in user

    f = profile.objects.get(user=request.user)

    if request.method=="POST" and is_last_subtopic:

        SubtopicProgress.objects.update_or_create(user=request.user, topic=material.studytopic, defaults={'completed': True})
        next_topic = StudyMaterial.objects.filter(studytopic__module=material.studytopic.module,studytopic__id__gt=material.studytopic.id).order_by('studytopic__id').first()
        if next_topic:
            next_subtopic = StudyMaterial.objects.filter(studytopic=next_topic.studytopic).order_by('id').first()
            return redirect('student:study_material', id=next_subtopic.id)
        else:
            return redirect('/dashboard')
    
    return render(request, 'study_material.html',{'material': material, 'next_material': next_material,'profile':f})

def course(request):
    uid=request.session.get('uid')
    f = profile.objects.get(user=request.user)
    courses = Course.objects.all()
    courseSort=set()
    for i in courses:
        courseSort.add(i.category)
    return render(request,'course.html',{'courses':courses,'courseSort':courseSort,'profile':f})


def sort(request,category):
    # uid=request.objects.filter(user=uid)
    courses = Course.objects.all()
    f = profile.objects.get(user=request.user)
    filtered_courses = Course.objects.filter(category__name=category)

student/templates/course.html
{%extends 'sidebar.html'%}
{%load static%}
{%block body%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Course Cards</title>
    <link rel="stylesheet" href="style.css">
</head>
<style>
    .rside{
    width: 150px;
    height: 100%;
    background-color: aquamarine;
    position: fixed;
    top: 0;
    right: 0;
    }
.rside h3{
    margin: 10px;
    padding: 10px;}

.sortBtn{
    padding: 0.5rem 1rem;
    background-color: #B0CB1F;
    border: none;
    text-decoration: none;
    border-radius: 10px;
}
.sortBtn a{
    text-decoration: none;
    color: white;
    font-size: 0.8rem;
    
}
</style>

<body class="course-body">
    {%if user.is_authenticated%}
    {%include 'navbar.html'%}


    <div class="cart">
        <a style="color: #B0CB1F;" href="{%url 'student:cartlist' %}"><i class="bi bi-cart">{{ cl}}</i></a>
    </div>

    <div class="">
        <h2>Sort</h2>
        <button class="sortBtn"><a href="{%url 'student:course' %}">All</a></button>
        {%for i in courseSort%}
        <button class="sortBtn"><a href="{%url 'student:sort' i%}">{{i}}</a></button>
        {%endfor%}
        </div>
    <div class="course-card-container">
        {%for course in courses%}
        <div class="course-card">
            <img src="{{course.image}}" alt="Data Science With Generative AI Course" height="20rem">
            <div class="course-info">
                <h2>{{course.name}}</h2>
                <p>{{course.details}}</p>
                <div class="position">
                    <div class="registration-status">
                        <span>Registrations Started</span>
                        <span class="start-date">Starts on {{course.date}}</span>
                    </div>
                    <div class="actions">
                        <button data-course={{course.id}} data-action="add"  class="explore-btn update-cart">Explore</button>
                        <a href="{%url 'student:addcart' course.id %}"><button class="buy-btn">Add to Cart</button></a>
                        </div>
                </div>
                </div>
        </div>
        {%endfor%}
    
        <!-- <div class="course-card">
            <div class="badge">Bestseller</div>
            <img src="banking-financial-image.jpg" alt="Post Graduate Certification in Banking, Financial Services & Insurance">
            <div class="course-info">
                <h2>Post Graduate Certification in Banking, Financial Services & Insurance</h2>
                <p>Program for individuals who wish to kickstart their career in the Private Banking Industry.</p>
                <div class="registration-status">
                    <span>₹ 25000 <del>40000</del></span>
                    <span class="start-date">Starts on 10 Jun 2024</span>
                </div>
                <div class="actions">
                    <button class="explore-btn">Explore</button>
                    <button class="register-btn">Register Now</button>
                </div>
            </div>
        </div>
    
        <div class="course-card">
            <div class="badge popular">Popular</div>
            <img src="full-stack-image.jpg" alt="Full Stack Development Course">
            <div class="course-info">
                <h2>Full Stack Development Course</h2>
                <p>Job Assistance | Gain Full Stack Development Expertise</p>
                <div class="registration-status">
                    <span>Registrations Started</span>
                    <span class="start-date">Starts on 14 Jun 2024</span>
                </div>
                <div class="actions">
                    <button class="explore-btn">Explore</button>
                    <button class="buy-btn">Buy Now</button>
                </div>
            </div>
        </div> -->
    </div>

    
    <script src="{%static 'js/cart.js'%}">

    </script>
    {%endif%}
</body>
</html>
{%endblock%}

student/templates/jobDetail.html
{%extends 'sidebar.html'%}
{%load static%}
{%block body%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <title>Job Listing</title>
</head>
<body class="jobBody">
    <div class="job-container">
        <div class="job-header">
            <div class="company-logo">
                <img src="logo.png" alt="Company Logo">
            </div>
            <div class="job-details">
                <h1>Technical Content Writer (Curriculum Developer)</h1>
                <p class="company-name">Itvedant Education Pvt Ltd</p>
                <p class="location">Thane</p>
                <p class="salary">₹ 15000 - 25000</p>
                <p class="vacancies">Vacancies: 2</p>
            </div>
            <div class="apply-button">
                <button>Apply</button>
            </div>
        </div>
        <div class="job-meta">
            <p class="posted-date">Posted: Yesterday</p>
            <p class="apply-before">Apply Before: Jul 04, 2024</p>
        </div>
        <div class="job-description">
            <h2>Job Description</h2>
            <ul>
                <li><strong>Content Creation:</strong> Develop engaging and informative technical content, including articles, tutorials, and course materials, tailored to the needs of Indian graduates.</li>
                <li><strong>Coding Expertise:</strong></li>
            </ul>
        </div>
        <div class="company-info">
            <h2>About Company</h2>
            <p><a href="https://www.itvedant.com/">https://www.itvedant.com/</a></p>
            <p>Kerom Building, 4th Floor, Near State Bank of India, Thane West, Thane, Maharashtra, India - 400601</p>
        </div>
    </div>
</body>
</html>
{% endblock %}

student/templates/login.html
{%load static%} {%block body%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link rel="stylesheet" href="{%static 'css/style.css'%}" />
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> -->

    <style>
      .forPass{
        /* margin-top: 1rem; */
        display: flex;
        gap: 8rem;
        position: relative;
        top: 3rem;
      }
      .forPass a{
        text-decoration: none;
        color: #B0CB1F;
      }
    </style>
  </head>
  <body class="body">
    <div class="logoImage">
      <img src="{%static 'image/itvedant_logo.svg'%}" alt="" />
    </div>

    <div class="flyLogo">
      <img src="{%static 'image/butterfly-border.png'%}" alt="" width="70%" />
    </div>

    <div class="flyLogo2">
      <img src="{%static 'image/butterfly-border.png'%}" alt="" width="60%" />
    </div>

    <div class="flyLogo3">
      <img src="{%static 'image/butterfly-border.png'%}" alt="" width="70%" />
    </div>
    <div class="msgError">
      {%include 'messages.html'%}
    </div>
    <div class="loginForm">
      <form action="" method="post" class="loginFormMain">
        {%csrf_token%}
        

        <div class="loginHeading">
          <h2>Login</h2>
          <p>to decode your dreams</p>
        </div>
        <table>
          <p>
            <input
              type="email"
              class="loginInput"
              name="username"
              maxlength="60"
              required
              id="id_username"
              placeholder="Enter your email"
            />
          </p>

          <p>
            <input
              type="password"
              name="password"
              class="loginInput"
              maxlength="30"
              required
              id="id_password"
              placeholder="Password"
            />
          </p>
          <tr>
            <td>
              <input type="submit" value="Login" class="mybtn loginbtn" />
            </td>
          </tr>

          
            
            
          
          
        </table>
        <div class="forPass">
          <!-- <a href="{%url 'student:password_reset'%}">Forgot Password?</a> -->

           <p> New User?<a href="{%url 'student:register'%}">Register</a></p>
        </div>
      </form>
      
    </div>
    
  </body>
</html>
{%endblock%}

student/templates/messages.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% for message in messages %}

<div
  class="alert alert-{{message.tags}} alert-dismissible fade show"
  role="alert"
>
  {{message}}
  
</div>

{% endfor %}

</body>
</html>

student/templates/navbar.html
{%if user.is_authenticated%}
<nav class="mynavbar">
    <div class="container">
        
        <div class="leftnav">
            <div>
                <i class="fa-solid fa-bars" id="bars" ></i>
            </div>
            <p>Welcome Back,</p>
            <p ><strong>{{profile.firstname}}</strong></p>
        </div>

        <div class="rightnav">
            <div class="ticket"></div>
            <div class="notification">

            </div> 

            <div class="self">
                <a href="" id="selfToggle" class="dropdown-toggle d-flex  self">
                    <img src="{{profile.img.url}}" alt="" class="common-profile selfImg" width="50px" height="50px">
                    <p class="student-name">
                        <!-- Profile -->
                        <!-- <sup class="new-badge float-right">New</sup>  -->
                        <span class="flex">
                            Welcome, {{profile.firstname}}!
                            <i class="fa-solid fa-caret-down"></i>
                        </span>
                    </p>
                </a>
            </div>

            <div class="profileToggle" id="profileId">
                <ul>
                    <li><a href="{%url 'student:profile'%}">My Profile</a></li>
                    <li><a href="{%url 'student:logout'%}">Logout</a></li>
                    
                </ul>
            </div>
        </div>
    </div>
</nav>
<script src="https://kit.fontawesome.com/2ae2e29bb9.js" crossorigin="anonymous"></script>
{%endif%}

student/templates/news.html
{%extends 'sidebar.html'%}
{%block body%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>
        .newsSearch{
            position: relative;
            left: 5rem;
            top: -5rem;
        }
        .newSearch{
            display: flex;
        }.mic2{
            height: 2rem;
            width: 2rem;
            position: relative;
            left: 6rem;
            top: 10rem;
            border-radius: 50%;
        }
        .search::placeholder{
            color: black;
        }
    </style>
</head>
<body>
    {%if user.is_authenticated%}
    {%include 'navbar.html'%}
    <h2 style="position: relative; top: 5rem; left: 3rem;">Latest Tech News</h2>
    <div class="newSearch">
        <form class="newsSearch" action="{%url 'student:news'%}" method="get" style="margin-top: 15rem;">
            <input type="text" name="q" class="search" id="searchInput2" placeholder="Enter or click on mic button to speak anything to search">
            
            <input class="lastBtn" type="submit" value="search">
            
    
        
        </form>
        <button class="mic2" onclick="startRecognition()">🎤</button>
    </div>
    
    <div class="newsContainer">
        
            {% for i in articles %}
        <div class="newsCard">
            <img src="{{ i.urlToImage }}" class="card-img-top" alt="..." width="100%" height="38%">
            <div class="card-body">
                <p class="card-text">{{ i.author }}</p>
                <h5 class="card-title">{{ i.title }}</h5>
                <!-- <p class="card-title">{{ i.source.name}}</p> -->
                <p class="card-text">{{ i.description }}</p>
                <hr>
                
            </div>
            <div class="publish">
                <small>Published At: {{ i.publishedAt }}</small>
            <a href="{{ i.url }}" class="see" target="_blank">See News</a>
            </div>
        </div>
        {% endfor %}
        
        I
        </div>
        {%endif%}
    </body>
</html>

<!-- <script>
    function startRecognition() {
        fetch("{% url 'student:recognize_speech' %}")
            .then(response => response.json())
            .then(data => {
                document.getElementById('searchInput2').value = data.query;
            })
            .catch(error => console.error('Error:', error));
    }
</script> -->

<script>
    function startRecognition() {

        // speak("Hello, how can I assist you today?");


        fetch("{% url 'student:recognize_speech' %}")
            .then(response => response.json())
            .then(data => {
                document.getElementById('searchInput2').value = data.query;
                // speak(`Hello ${data.first_name}, how can I assist you today?`);
                speak(data.query);
                
            })
            .catch(error => console.error('Error:', error));
    }

    // function speak(text) {
    //     var msg = new SpeechSynthesisUtterance(text);
    //     window.speechSynthesis.speak(msg);
    // }

    // Initial greeting
    
</script>
{%endblock%}

student/templates/password_reset_confirm.html
  <h2>Set a new password</h2>
  <form method="post" action="">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Set new password</button>
  </form>

student/templates/password_reset_done.html
  <h2>Password reset sent</h2>
  <p>An email has been sent with instructions to reset your password. Please check your inbox.</p>

student/templates/password_reset_form.html
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset my password</button>
</form>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

{% block content %}
  <p>Instructions for resetting your password will be sent to the provided email address if it is associated with an account.</p>
{% endblock %}

student/templates/sidebar.html
{%load static%}
<!DOCTYPE html>

<link rel="stylesheet" href="{%static 'css/style.css'%}" />
<!-- <link rel="stylesheet" href="{%static 'css/bmin.css'%}"> -->
<link
  rel="”stylesheet”"
  href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
/>
<link rel="icon" type="image/x-icon" href="{% static 'image/favicon (1).ico' %}">
<!-- Option 1: Include in HTML -->
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
/>

<body>
  <div class="sidebar" id="sidebars">
    <div class="logo">
      <a href="{%url 'student:dashboard'%}">
        <img
          src="https://wingz.itvedant.com/images/itvedant_logo.svg"
          alt=""
          width="62%"
          height="70px"
        />
      </a>
    </div>
    <ul>
      {%if user.is_authenticated%}
      <li class="sidebarLink">
        <i class="bi bi-speedometer2"></i
        ><a href="{%url 'student:dashboard'%}"><span>Dashboard</span></a>
      </li>
      <li class="sidebarLink">
        <i class="bi bi-people-fill"></i
        ><a href="{%url 'student:interview'%}">Interview Questions</a>
      </li>
      {% comment %}
      <li><a href="">Job Opening Details</a></li>
      {% endcomment %}
      <li class="sidebarLink">
        <i class="bi bi-clipboard"></i>
        <a href="{%url 'student:profile'%}">Profile</a>
      </li>
      <li class="sidebarLink">
        <i class="bi bi-book"></i>
        <a href="{%url 'student:course'%}">New Courses</a>
      </li>
      <li class="sidebarLink">
        <i class="bi bi-question-circle"></i>
        <a href="{%url 'student:news'%}">News</a></li>
      <!-- {% comment %} <li class="sidebarLink">
        <i class="bi bi-book"></i>
        <a href="">3A</a></li> {% endcomment %} -->
      <li class="sidebarLink">
        <i class="bi bi-box-arrow-left"></i>
        <a href="{%url 'student:logout'%}">Logout</a></li>
    </ul>
    {%else%}
    <!-- <li><a href="{%url 'student:login'%}">Login</a></li>
        <li><a href="{%url 'student:register'%}">Registration Form</a></li> -->
    <h1>You have been logged out</h1>
    <a href="/handleLogin">Click here</a> <span>to login</span>
    {%endif%}

    <div class="manager">
      <h3>Relationship Manager</h3>
      <hr />
      <div class="managerDetails">
        <div class="managerImg"></div>
        <p>ABC</p>

        <div class="managerContact">
          <div class="contIcon"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="main">{%block body%} {%endblock%}</div>

  <script src="{%static 'js/script.js'%}"></script>
  <script
    src="https://kit.fontawesome.com/2ae2e29bb9.js"
    crossorigin="anonymous"
  ></script>
</body>

student/templates/success.html
<style>
    .text-center{
        text-align: center;
    }
</style>

<div class="text-center">
    <img src="https://www.svgrepo.com/show/157817/success.svg" alt="" class='img-fluid' style="height: 200px;">
    <h2>Thanks Your Payment has been received</h2>

</div>

<div class="text-center">
    Click here to go the dashboard page <a href="{%url 'student:dashboard'%}">Dashboard</a>
</div>